name: Test shell scripts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Bats
        run: sudo apt-get update && sudo apt-get install -y bats
      - name: Run Bats tests
        run: bats tests/
